-- DELETE FROM phone_color;
-- DELETE FROM phone_sensor;
-- DELETE FROM phone_camera;
-- DELETE FROM specification;
-- DELETE FROM phone;
-- DELETE FROM sensor;
-- DELETE FROM camera;
-- DELETE FROM color;