ALTER TABLE camera AUTO_INCREMENT = 1;
ALTER TABLE color AUTO_INCREMENT = 1;
ALTER TABLE phone AUTO_INCREMENT = 1;
ALTER TABLE phone_camera AUTO_INCREMENT = 1;
ALTER TABLE phone_color AUTO_INCREMENT = 1;
ALTER TABLE phone_sensor AUTO_INCREMENT = 1;

